# Generated by Django 3.1.2 on 2020-12-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_image',
            new_name='UPLOAD_LEAF_IMAGE',
        ),
    ]
